Be tolerant to matching refresh rates that are a few points off.
emersion/kanshi pull request #64
Opened 2020-01-10 20:13 UTC by jameswalmsley

When specifying a referesh rate like @60Hz kanshi expects an absolute match.

Many monitors have refresh timings that are slightly off these absolute values.

e.g.  

"current_mode": {
    "width": 2560,
    "height": 1440,
    "refresh": 60012
  }

I propose to tolerate a deviation of +/- 50 1/1000th Hz.

2020-01-10 22:04 UTC, emersion commented on main.c
> +	return (abs(v) < 50);
Style: he outer parentheses are unnecessary.

2020-01-10 22:06 UTC, emersion requested changes
Thanks for your PR! The idea LGTM, just a little style nit.

2020-01-10 22:07 UTC, emersion commented
At some point we should probably pick the highest refresh if it isn't specified, or the closest refresh if specified.

2020-01-10 23:30 UTC, jameswalmsley commented
Thanks! No problem on the style nit.

I've updated and pushed.

The +/- 50 is just a magic number, would you like a define, or the ability to
configure this? Not sure it really matters.

Agree on the auto-select maximum refresh rate.

I'll have a look into it.

2020-01-11 09:11 UTC, emersion approved these changes
LGTM, thanks!

2020-01-11 09:11 UTC, merged